### ISSUE TITLE
stream just stops

### ISSUE THREAD

**Issue by kamil-malinski** [Leask/halbot#8]
Hi!

Since the release [1989.6.27](https://github.com/Leask/halbot/commit/e2e82c2ed2c6f1ab61c379fe9dc27ae2ce9e381a) the stream often just stops. There's nothing in the log, the stream just stops and the message stays incomplete.

Kamil

**Comment by Leask** [comment]
Thanks! I know this issue because I am testing a new feature, that enables the user to click to select the response. And there is a bug in the button markup.  I am sorry this is a side project I don’t have enough time to test it before releasing versions. I have a better version under development that fixed this issue and I think I can finish it today. 😄

**Comment by kamil-malinski** [comment]
no worries, we appreciate all the work you put into this!

**Comment by Leask** [comment]
And as I know the streaming issue only happens while using the bing ai engine, right? Can you confirm this?

**Comment by kamil-malinski** [comment]
> And as I know the streaming issue only happens while using the bing ai engine, right? Can you confirm this?

yes, it happens with the Bing engine

**Comment by Leask** [comment]
Ok, cool, so the upcoming version will make it work again. 😃

**Comment by Leask** [comment]
fixed 🍻
